
ALTER TABLE public.challenge_subscriptions
  ADD COLUMN IF NOT EXISTS daily_goal_points INTEGER NOT NULL DEFAULT 70,
  ADD COLUMN IF NOT EXISTS total_goal_points INTEGER NOT NULL DEFAULT 2000;

ALTER TABLE public.challenge_daily_tasks
  ADD COLUMN IF NOT EXISTS task_title TEXT,
  ADD COLUMN IF NOT EXISTS task_type TEXT,
  ADD COLUMN IF NOT EXISTS task_prompt TEXT,
  ADD COLUMN IF NOT EXISTS max_points INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS submission TEXT,
  ADD COLUMN IF NOT EXISTS awarded_points INTEGER,
  ADD COLUMN IF NOT EXISTS feedback TEXT;
